### PR TITLE
Unpin dask and distributed for 24.08 development

### PR DESCRIPTION
**Pull request by rjzamora**
Upins dask and distributed for 24.08 development.

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @rjzamora !

**Review by vyasr — APPROVED** [review]
This seems a bit delayed, do we know if anything will break when we merge this? No worries if not, we have to deal with it anyway, just asking to be prepared.

**Comment by rjzamora** [comment]
>This seems a bit delayed, do we know if anything will break when we merge this? No worries if not, we have to deal with it anyway, just asking to be prepared.

Completely agree - This was an oversight, and we unfortunately don't know for sure if things will break. I'm in the process of testing for obvious problems locally, but the only way to catch everything is to use the updated rapids-dask-dependency nightly in CI across RAPIDS. The good news is that I will be available next week to tackle problems if/when they arise.

**Pull request merged**
