### PR TITLE
Generalize patching to support vendoring

### PR DESCRIPTION
**Pull request by vyasr**
This PR makes a number of significant changes to the patching infrastructure:
1. This PR reorganizes the patching logic to be based on a more principled approach. Rather than maintaining lists of patch functions that are each responsible for filtering modules to apply themselves to, patches are organized in the patches directory in a tree structure matching dask itself. Patches are found and run by importing the same relative paths within the `patches` directory corresponding to a particular dask or distributed module.
2. It adds proper support for patching submodules. Previously the loader was being disabled whenever a real dask module was being imported, but this is problematic because if some dask modules import others they will pre-populate `sys.modules` with the real modules and therefore the loader will never be used for loading a patched version of the submodule.
3. Patches are no longer just functions applied to modules, they are arbitrary functions executed when a module is imported. As a result, a wider range of modifications is possible than was previously allowed. In particular:
4. The more general functions allow the entire module import to be hijacked and redirected to other modules.
5. The new framework is used to vendor a patched version of the accessor.py module in dask, which resolves the issues observed in https://github.com/dask/dask/pull/11035.

### CODE REVIEW

**Comment by vyasr** [comment]
For posterity, this is a redo of #38 because that PR was merged without squashing.

**Comment by vyasr** [comment]
This is blocked on #5815

**Review by rjzamora — APPROVED** [review]
Thanks!

**Pull request merged**
