### PR TITLE
Backport patching functionality from 24.06

### PR DESCRIPTION
**Pull request by vyasr**
This PR backports #27, #37, and #39 to 24.04

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Let's backport as-is, and tweak in follow-up PRs if needed.

**Comment by rjzamora** [comment]
>Let's backport as-is, and tweak in follow-up PRs if needed.

Seems fine to me. The easiest way to test is honestly to get this merged. The only tweak I have in mind is to avoid installing `DaskLoader` for python<3.11.9, but I'd like to test with the patching in place either way.

**Review by rjzamora — APPROVED** [review]
Local testing looks good to me. Thanks @vyasr !

I think it makes sense to merge this now. We could submit a test PR to cudf first to "check CI", but I don't think that saves us any time given that 24.04 is now frozen anyway. Thoughts @bdice ?

**Comment by bdice** [comment]
@rjzamora I agree we should merge. I’ll request an admin merge from ops since the branch is frozen.

**Pull request merged**
